#! /bin/sh

# ┌─┐┬─┐┌─┐┌─┐┌┬┐
# │ ┬├┬┘├┤ ├┤  │
# └─┘┴└─└─┘└─┘ ┴

# Get user
user="Miguel"
showWeather="true"

# Colors and palette method stolen
# from dylanaraps pftech:
# https://github.com/dylanaraps/pfetch

c0='[0m'
c1='[31m'
c2='[32m'
c3='[33m'
c4='[34m'
c5='[35m'
c6='[36m'
c7='[37m'
c8='[38m'
c9='^[[37m'

# Greeting message

h=$(date +%H)

if [ $h -lt 6 ]; then
  greet="Go to sleep 🌑 "
elif [ $h -lt 12 ]; then
  greet="Good ${c2}Morning 🌄 "
elif [ $h -lt 18 ]; then
  greet="Good ${c3}Afternoon 🌆 "
else
  greet="Good ${c5}Night 🌉 "
fi

# Weather module

if [ $showWeather == "true" ]; then
  temp=$(curl -s 'wttr.in?format=%C')
  weather="${c0}It's ${c4}${temp}"
fi

# Main print

cat <<-EOF

 Hi ${c2}${user}${c0}, ${greet}

 ${weather}

EOF
